NAME = libft.a

FILEC =	ft_strlen.c \
		ft_isalpha.c \
		ft_isdigit.c \
		ft_isalnum.c \
		ft_isascii.c \
		ft_isprint.c \
		ft_toupper.c \
		ft_tolower.c \
		ft_atoi.c \
		ft_strcmp.c \
		ft_strncmp.c \
		ft_memcmp.c \
		ft_bzero.c \
		ft_memset.c \
		ft_memmove.c \
		ft_memchr.c \
		ft_memcpy.c \
		ft_memccpy.c \
		ft_strdup.c \
		ft_strcpy.c \
		ft_strncpy.c \
		ft_strcat.c \
		ft_strncat.c \
		ft_strchr.c \
		ft_strrchr.c \
		ft_strstr.c \
		ft_strnstr.c \
		ft_strlcat.c \
		ft_memalloc.c \
		ft_memdel.c \
		ft_strnew.c \
		ft_strdel.c \
		ft_strclr.c \
		ft_striter.c \
		ft_striteri.c \
		ft_strmap.c \
		ft_strmapi.c \
		ft_strequ.c \
		ft_strnequ.c \
		ft_strsub.c \
		ft_strjoin.c \
		ft_strtrim.c \
		ft_itoa.c \
		ft_strsplit.c \
		ft_putchar.c \
		ft_putstr.c \
		ft_putendl.c \
		ft_putnbr.c \
		ft_putchar_fd.c \
		ft_putstr_fd.c \
		ft_putendl_fd.c \
		ft_putnbr_fd.c \
		ft_lstnew.c \
		ft_lstdelone.c \
		ft_lstdel.c \
		ft_lstadd.c \
		ft_lstiter.c \
		ft_lstmap.c \
		ft_countword.c \
		ft_freearr.c \
		ft_intsize.c \
		ft_swappoint.c \
		ft_sqrt.c \
		ft_countc.c \
		ft_l_itoa.c \
		ft_ltoa_base.c \
		ft_utoa_base.c \
		ft_utoa_base_little.c \

FILEO = $(FILEC:.c=.o)

DIRO = ../obj

LIB = libft.h

FLAG = -Wall -Wextra -Werror

all: $(NAME)

$(NAME): $(FILEC)
	@gcc -c $(FILEC) -I $(LIB)
	@ar -rc $(NAME) $(FILEO)
	@ranlib $(NAME)

copy:
	@mkdir -p $(DIRO)
	@cp $(FILEO) $(DIRO)

clean:
	@rm -rf $(FILEO)
	@rm -rf $(DIRO)

fclean: clean
	@rm -rf $(NAME)

re: fclean all 
